version: '2'
services:
    python:
        build:
            context: .
            dockerfile: ./docker/Dockerfile-cpu
        container_name : ocr
        image: "tuananhbk/ocr:cpu"
        ports:
            - "8889:8889"
        volumes:
            - ".:/data"
        user: anh
        working_dir: /data
        tty: true
        command: jupyter notebook --ip=0.0.0.0 --port=8889 --NotebookApp.password='sha1:4018b457b8a9:84c65a176a549c58609c3cf38fa50b4b1b12b808'
    anaconda:
        image: "tuananhbk/ocr:cpu" 
        ports:
            - "8899:8899"
        volumes:
            - ${SUBL_PACKAGE_PATH}/Packages/Anaconda:/opt/anaconda
            - ".:/data"
        depends_on:
            - python
        user: root
        entrypoint: /opt/anaconda/anaconda_server/docker/start python 8899 docker /opt/anaconda
        tty: true
